[client]
showSidebarNavigation = false

[client]
# Chuyển thanh công cụ sang chế độ "Người xem" (Viewer)
# Chế độ này sẽ khóa và giấu toàn bộ các tính năng nguy hiểm (Clear Cache, Deploy...)
toolbarMode = "viewer"

[ui]
# Tắt nút Menu 3 chấm ở góc trên bên phải
hideTopBar = true